### ISSUE TITLE
github.....v4.5.3/win32-x64-59_binding.node doesnt exist

### ISSUE THREAD

**Issue by erwin-van-maasakkers** [laravelnews/laravel-twbs4#15] opened 2017-11-29 21:24 UTC
After the 'npm install' i get an error: 
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

I tested the URL in a browser and it really does give van error 404.

Maybe use V4.6.0, there is this file available?!

@paulredmond: you requested more information:
I'm not very experianced with NPM but when i follow the instructions it all goes well until i start the npm install. After a while i get the following output:

> node-sass@4.5.3 install C:\xampp\htdocs\on55\node_modules\node-sass
> node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":
HTTP error 404 Not Found

As i said, the URL really doesnt exist if i enter it in a browser. A check on packagist.com also confirms that the file win32-x64-59_binding.node in version V4.5.3. doesnt exist. Only in V4.6.0.

I'm not sure if its a problem in the package, or maybe i'm doing something wrong. Please advise what else i can try to get more info or better results.

**Comment by paulredmond** [comment] 2017-11-29 21:29
@erwinmnl do you believe this is an issue caused by this package? If so, please report as many details as possible and a way to reproduce.

**Comment by paulredmond** [comment] 2017-11-29 21:30
I am going to close this issue until you provide more information, thanks!

**Closed as completed by paulredmond** 2017-11-29 21:30 UTC
